ALTER TABLE t_order ADD COLUMN IF NOT EXISTS calculated_amount DECIMAL(18,2);
ALTER TABLE t_order ADD COLUMN IF NOT EXISTS fee_amount DECIMAL(18,2);
ALTER TABLE t_order ADD COLUMN IF NOT EXISTS fee_detail TEXT;
ALTER TABLE t_order ADD COLUMN IF NOT EXISTS remark VARCHAR(500);
