server:
  port: 8082

spring:
  application:
    name: fin-core-payment
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: dev
        enabled: false
      config:
        enabled: false
        import-check:
          enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/fincore?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: fincore
    password: fincore123

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
